# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Krystal White"
resume_title:                   "Reporter, Blogger, & Journalist"
resume_contact_email:
  "krystalwhite9@gmail.com"
resume_header_contact_info: "742 Evergreen Terrace, Springfield | 555-7334 | homerjsimpson@youremailaddress.com"
resume_header_intro: "Outstanding student athlete with a strong desire to become a part of a sports jurnalism program seeking an opportunities to develop skills and techniques that will prepare me for, and help me gain entry to a college level journalism program."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           https://twitter.com/search?q=imasportsmaniac&src=typd
  resume_dribbble_url:          
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          https://www.linkedin.com/in/krystal-white-2a6b11144/
  # resume_instagram_url:         https://www.instagram.com/imasportsmaniac/?hl=en
  resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
